### ISSUE TITLE
VUELVE A REPETIR EL CODIGO: HAY QUE HACER QUE NUNCA REPITA LOS CODIGOS 

### ISSUE THREAD

**Issue by oscarito2016** [kplian/sis_operman#10]
![image](https://cloud.githubusercontent.com/assets/21204779/17944393/87f0c684-6a0d-11e6-84a9-5560e1c2f68e.png)

**Comment by rchumacero** [comment]
Resuelto: se agregar constraint unique en base de datos para el campo codigo de la tabla de mantenimientos predefinidos
