### ISSUE TITLE
CAMBIAR LOGO Y BORRAR CODIGO Y FECHA

### ISSUE THREAD

**Issue by oscarito2016** [kplian/sis_operman#3]
![image](https://cloud.githubusercontent.com/assets/21204779/17943733/ab9d1748-6a0a-11e6-8dd1-18afd2b77952.png)
Cambiar el Logo en TODOS LOS REPORTES, y borrar el codigo y fecha en todos los reportes

**Comment by rchumacero** [comment]
Resuelto: se restaura los reportes ya modificados
